name: Docker Image CI

on:
  push:
    branches: [ "master", "cross_platform" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v4
      
      # Add support for more platforms with QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Create timestamp
        run: |
          STAMP=$(date +"%Y-%m-%d_%H.%M.%S")
          echo "GDB_TIMESTAMP=$STAMP" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.extract_branch.outputs.branch }}_${{ env.GDB_TIMESTAMP }}_${{ github.sha }}
            type=raw,value=${{ steps.extract_branch.outputs.branch }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container

      - uses: docker/build-push-action@v5.3.0
        with:
          platforms: linux/amd64,linux/arm64/v8
          file: Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
